## COMMON PROPERTIES
spring:
  profiles: 
    active: dev

##webcontents 설정
  thymeleaf:
    prefix: classpath:/static/view/
  
  mvc:
    view:
#      prefix: /src/main/frontend/public/view/
      suffix: .html

      
##DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.96.119:3306/hangagu?serverTimezone=UTC&characterEncoding=UTF-8
    username: sylim
    password: Hangagu1!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
#        dialect: kr.co.hangagu.common.config.CustomMysqlDialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
## 시큐리티 설정

