## COMMON PROPERTIES
spring:
  profiles: 
    active: dev

  ##DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.242.115:3306/kangil_test?serverTimezone=UTC&characterEncoding=UTF-8
    username: kichoi
    password: Hangagu1!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
## 시큐리티 설정
